import { slugifyKnowledgeTitle } from "@/lib/knowledge-utils";

type TopicInput = {
  title: string;
  summary?: string;
  slug?: string;
};

type CategoryInput = {
  id: string;
  index: string;
  title: string;
  titleZh: string;
  shortLabel: string;
  description: string;
  icon: string;
  accent: string;
  featured?: boolean;
  topics: TopicInput[];
};

function makeArticle(topic: TopicInput) {
  return {
    title: topic.title,
    slug: topic.slug ?? slugifyKnowledgeTitle(topic.title),
    summary:
      topic.summary ??
      `Engineering reference on ${topic.title} for wireless power system design, integration, and deployment.`,
    readTime: "6 min",
  };
}

function makeCategory(input: CategoryInput) {
  return {
    id: input.id,
    index: input.index,
    title: input.title,
    titleZh: input.titleZh,
    shortLabel: input.shortLabel,
    description: input.description,
    icon: input.icon,
    accent: input.accent,
    featured: input.featured ?? false,
    articles: input.topics.map(makeArticle),
  };
}

const categoryInputs: CategoryInput[] = [
  {
    id: "wireless-charging-fundamentals",
    index: "01",
    title: "Wireless Charging Fundamentals",
    titleZh: "无线充电基础",
    shortLabel: "Fundamentals",
    description: "Core concepts, transfer modes, coupling principles, and wireless power terminology.",
    icon: "fundamentals",
    accent: "from-blue-600 to-cyan-400",
    topics: [
      { title: "What is Wireless Charging?" },
      { title: "History of Wireless Power" },
      { title: "Inductive Power Transfer (IPT)" },
      { title: "Magnetic Resonance Charging" },
      { title: "Capacitive Power Transfer" },
      { title: "Far-Field Wireless Power" },
      { title: "RF Wireless Power" },
      { title: "Microwave Power Transfer" },
      { title: "Laser Wireless Power" },
      { title: "Near-Field vs Far-Field" },
      { title: "Static vs Dynamic Charging" },
      { title: "One-to-One vs One-to-Many Charging" },
      { title: "Power Transfer Principles" },
      { title: "Energy Conversion Fundamentals" },
      { title: "Coupling Mechanisms" },
      { title: "Wireless Power Terminology" },
    ],
  },
  {
    id: "resonant-wireless-power",
    index: "02",
    title: "Resonant Wireless Power Technology",
    titleZh: "磁共振无线充电",
    shortLabel: "Resonant WPT",
    description: "Resonant theory, compensation topologies, soft switching, and power regulation.",
    icon: "resonant",
    accent: "from-[#0B5FFF] to-blue-400",
    topics: [
      { title: "Resonant Theory" },
      { title: "Coupling Coefficient" },
      { title: "Quality Factor (Q)" },
      { title: "Frequency Selection" },
      { title: "Series Resonance" },
      { title: "Parallel Resonance" },
      { title: "LCC Compensation" },
      { title: "LCL Compensation" },
      { title: "LLC Resonance" },
      { title: "Double-Sided Compensation" },
      { title: "Frequency Splitting" },
      { title: "Soft Switching" },
      { title: "ZVS" },
      { title: "ZCS" },
      { title: "Power Regulation" },
      { title: "Resonant Stability" },
    ],
  },
  {
    id: "coil-engineering",
    index: "03",
    title: "Coil Engineering",
    titleZh: "线圈设计",
    shortLabel: "Coil Design",
    description:
      "Fifty engineering topics on coil geometries, magnetics, conductors, alignment, simulation, manufacturing, and reliability.",
    icon: "coil",
    accent: "from-indigo-600 to-violet-400",
    topics: [
      { title: "Coil Fundamentals" },
      { title: "Spiral Coil" },
      { title: "DD Coil" },
      { title: "Circular Coil" },
      { title: "Rectangular Coil" },
      { title: "Multi-Coil Array" },
      { title: "Three-Dimensional Coil" },
      { title: "Litz Wire" },
      { title: "Ferrite Materials" },
      { title: "Magnetic Shielding" },
      { title: "Coil Alignment" },
      { title: "Misalignment" },
      { title: "Air Gap Design" },
      { title: "Coupling Optimization" },
      { title: "Coil Simulation" },
      { title: "Coil Manufacturing" },
      { title: "Bipolar Coil" },
      { title: "Unipolar Coil" },
      { title: "Solenoid Coil" },
      { title: "Planar Coil" },
      { title: "PCB Coil" },
      { title: "Bifilar Winding" },
      { title: "Coil Turns Design" },
      { title: "Coil Pitch and Spacing" },
      { title: "Inner and Outer Diameter" },
      { title: "Self-Inductance Design" },
      { title: "Mutual Inductance Design" },
      { title: "Coil Resistance and ESR" },
      { title: "Skin Effect in Coils" },
      { title: "Proximity Effect" },
      { title: "Coil Thermal Design" },
      { title: "Coil Insulation" },
      { title: "Potting and Encapsulation" },
      { title: "Copper vs Aluminum Conductors" },
      { title: "Nanocrystalline Cores" },
      { title: "Ferrite Tile Layout" },
      { title: "Flux Guides" },
      { title: "Leakage Flux Control" },
      { title: "Transmitter Pad Coil Stack" },
      { title: "Receiver Coil Packaging" },
      { title: "Coil-to-Chassis Interaction" },
      { title: "Foreign Metal Near Coils" },
      { title: "High-Power Coil Design" },
      { title: "Coil Vibration and Stress" },
      { title: "Coil Aging and Reliability" },
      { title: "Coil Testing and Measurement" },
      { title: "Impedance Analyzer Methods" },
      { title: "Finite Element Magnetics" },
      { title: "Coil Cost Optimization" },
      { title: "Coil Design Checklist" },
    ],
  },
  {
    id: "power-electronics",
    index: "04",
    title: "Power Electronics",
    titleZh: "功率电子",
    shortLabel: "Power Electronics",
    description:
      "Fifty classic power-electronics topics for wireless chargers — conversion stages, WBG devices, drivers, losses, magnetics, protection, and EMC.",
    icon: "power",
    accent: "from-amber-600 to-orange-400",
    topics: [
      { title: "Rectifiers" },
      { title: "Inverters" },
      { title: "DC/DC Converters" },
      { title: "AC/DC Conversion" },
      { title: "Synchronous Rectification" },
      { title: "MOSFET Selection" },
      { title: "GaN Technology" },
      { title: "SiC Technology" },
      { title: "Gate Drivers" },
      { title: "Power Stage Design" },
      { title: "Switching Loss" },
      { title: "Conduction Loss" },
      { title: "Thermal Design" },
      { title: "Power Density" },
      { title: "EMI Reduction" },
      { title: "EMC Design" },
      { title: "Power Factor Correction" },
      { title: "Full-Bridge Inverter" },
      { title: "Half-Bridge Inverter" },
      { title: "Class-D Amplifier Stages" },
      { title: "Buck Converter" },
      { title: "Boost Converter" },
      { title: "Buck-Boost Converter" },
      { title: "LLC Resonant Converter" },
      { title: "Phase-Shifted Full Bridge" },
      { title: "Current-Fed Converters" },
      { title: "Voltage-Fed Converters" },
      { title: "IGBT in Wireless Power" },
      { title: "Diode Selection" },
      { title: "Snubber Circuits" },
      { title: "Bootstrap Gate Drive" },
      { title: "Isolated Gate Drivers" },
      { title: "Dead-Time Design" },
      { title: "Shoot-Through Protection" },
      { title: "DC Bus Design" },
      { title: "DC Link Capacitors" },
      { title: "Input EMI Filter" },
      { title: "Common-Mode Chokes" },
      { title: "PCB Layout for Power" },
      { title: "Current Sensing" },
      { title: "Voltage Sensing" },
      { title: "Overcurrent Protection" },
      { title: "Overvoltage Protection" },
      { title: "Soft Start" },
      { title: "Efficiency Mapping" },
      { title: "Loss Breakdown Analysis" },
      { title: "Heatsink and Cooling" },
      { title: "Parasitic Inductance" },
      { title: "Switching Node Design" },
      { title: "Power Electronics Checklist" },
    ],
  },
  {
    id: "intelligent-power-control",
    index: "05",
    title: "Intelligent Power Control",
    titleZh: "智能功率控制",
    shortLabel: "AI Power Control",
    description:
      "SiCore core competency — adaptive control, AI optimization, detection, and autonomous charging intelligence.",
    icon: "ai",
    accent: "from-violet-600 to-fuchsia-400",
    featured: true,
    topics: [
      { title: "Adaptive Power Control" },
      { title: "AI Optimization" },
      { title: "Digital Power" },
      { title: "Dynamic Frequency Tracking" },
      { title: "Dynamic Impedance Matching" },
      { title: "Load Detection" },
      { title: "Foreign Object Detection" },
      { title: "Living Object Detection" },
      { title: "Real-Time Efficiency Optimization" },
      { title: "Predictive Maintenance" },
      { title: "Smart Energy Scheduling" },
      { title: "Battery Health Monitoring" },
      { title: "Self Calibration" },
      { title: "Autonomous Charging" },
    ],
  },
  {
    id: "charging-stations",
    index: "06",
    title: "Charging Stations",
    titleZh: "智能充电站",
    shortLabel: "Charging Stations",
    description: "Docking systems, fleet charging, autonomous alignment, and cloud-managed infrastructure.",
    icon: "station",
    accent: "from-cyan-600 to-teal-400",
    topics: [
      { title: "Charging Dock" },
      { title: "Charging Pad" },
      { title: "Docking Technology" },
      { title: "Automatic Alignment" },
      { title: "Vision Assisted Docking" },
      { title: "Fleet Charging" },
      { title: "Opportunity Charging" },
      { title: "High Availability Charging" },
      { title: "Charging Infrastructure" },
      { title: "Multi-Robot Charging" },
      { title: "Autonomous Docking" },
      { title: "Smart Charging Management" },
      { title: "Cloud Charging Network" },
    ],
  },
  {
    id: "battery-energy-management",
    index: "07",
    title: "Battery & Energy Management",
    titleZh: "电池与能源管理",
    shortLabel: "Battery & Energy",
    description: "Battery chemistry, BMS, SOC/SOH, safety, balancing, and hybrid energy architectures.",
    icon: "battery",
    accent: "from-emerald-600 to-green-400",
    topics: [
      { title: "Lithium Battery Basics" },
      { title: "Battery Chemistry" },
      { title: "SOC" },
      { title: "SOH" },
      { title: "BMS" },
      { title: "Fast Charging" },
      { title: "Battery Safety" },
      { title: "Thermal Management" },
      { title: "Cell Balancing" },
      { title: "Energy Optimization" },
      { title: "Hybrid Energy Systems" },
      { title: "Supercapacitors" },
    ],
  },
  {
    id: "embedded-systems",
    index: "08",
    title: "Embedded Systems",
    titleZh: "嵌入式",
    shortLabel: "Embedded",
    description: "MCU/DSP selection, firmware architecture, real-time control, and OTA diagnostics.",
    icon: "embedded",
    accent: "from-slate-700 to-slate-500",
    topics: [
      { title: "MCU Selection" },
      { title: "DSP" },
      { title: "ARM Cortex" },
      { title: "STM32" },
      { title: "RTOS" },
      { title: "Firmware Architecture" },
      { title: "Real-Time Control" },
      { title: "PWM" },
      { title: "ADC" },
      { title: "Digital Filtering" },
      { title: "Fault Detection" },
      { title: "Diagnostics" },
      { title: "OTA Updates" },
    ],
  },
  {
    id: "thermal-engineering",
    index: "09",
    title: "Thermal Engineering",
    titleZh: "热设计",
    shortLabel: "Thermal",
    description: "Heat transfer, simulation, cooling strategies, and thermal protection for high-power systems.",
    icon: "thermal",
    accent: "from-orange-600 to-red-400",
    topics: [
      { title: "Heat Transfer" },
      { title: "Thermal Simulation" },
      { title: "Heat Sink" },
      { title: "PCB Thermal Design" },
      { title: "Thermal Interface Materials" },
      { title: "Cooling Methods" },
      { title: "High Power Thermal Design" },
      { title: "Temperature Monitoring" },
      { title: "Thermal Protection" },
    ],
  },
  {
    id: "emi-emc-engineering",
    index: "10",
    title: "EMI / EMC Engineering",
    titleZh: "EMI / EMC 工程",
    shortLabel: "EMI / EMC",
    description: "Emission control, shielding, filtering, standards, and compliance testing.",
    icon: "emi",
    accent: "from-rose-600 to-pink-400",
    topics: [
      { title: "EMI Basics" },
      { title: "EMC Standards" },
      { title: "Shielding" },
      { title: "Grounding" },
      { title: "Filtering" },
      { title: "CISPR" },
      { title: "FCC" },
      { title: "CE Compliance" },
      { title: "Conducted Emission" },
      { title: "Radiated Emission" },
      { title: "Immunity Testing" },
    ],
  },
  {
    id: "safety-engineering",
    index: "11",
    title: "Safety Engineering",
    titleZh: "安全工程",
    shortLabel: "Safety",
    description: "Functional safety, protection systems, FOD/LOD, and emergency shutdown design.",
    icon: "safety",
    accent: "from-red-600 to-orange-500",
    topics: [
      { title: "Functional Safety" },
      { title: "Electrical Isolation" },
      { title: "Overcurrent Protection" },
      { title: "Overvoltage Protection" },
      { title: "ESD" },
      { title: "Surge Protection" },
      { title: "FOD" },
      { title: "LOD" },
      { title: "Thermal Protection" },
      { title: "Emergency Shutdown" },
    ],
  },
  {
    id: "industry-standards",
    index: "12",
    title: "Industry Standards",
    titleZh: "行业标准",
    shortLabel: "Standards",
    description: "Qi, automotive, IEC/UL, regulatory compliance, and material substance requirements.",
    icon: "standards",
    accent: "from-blue-700 to-indigo-500",
    topics: [
      { title: "Qi" },
      { title: "Qi2" },
      { title: "AirFuel" },
      { title: "SAE J2954" },
      { title: "IEC Standards" },
      { title: "UL Standards" },
      { title: "FCC Requirements" },
      { title: "CE Requirements" },
      { title: "RoHS" },
      { title: "REACH" },
    ],
  },
  {
    id: "autonomous-charging",
    index: "13",
    title: "Autonomous Charging",
    titleZh: "自主充电",
    shortLabel: "Autonomous Charging",
    description:
      "What autonomous charging is, when to use wireless or contact charging, and how plug-free docking completes the cycle.",
    icon: "ai",
    accent: "from-[#0B5FFF] to-cyan-400",
    featured: true,
    topics: [
      {
        title: "What is Autonomous Charging?",
        slug: "what-is-autonomous-charging",
        summary:
          "Autonomous charging is the system that lets a machine find power, dock, charge, report energy status, and return to work without a person plugging in a cable.",
      },
      {
        title: "Wireless vs Contact Charging for AMRs",
        slug: "wireless-vs-contact-charging-for-amrs",
        summary:
          "How to choose wireless charging or contact charging for an AMR or AGV, and why many fleets use both inside one autonomous charging platform.",
      },
      {
        title: "How Plug-Free Docking Works",
        slug: "how-plug-free-docking-works",
        summary:
          "Plug-free docking is the mechanical and control step that puts a machine on a charger without a person mating a connector.",
      },
    ],
  },
];

export const knowledgeCategories = categoryInputs.map(makeCategory);

export type KnowledgeCategoryId = (typeof knowledgeCategories)[number]["id"];

export const knowledgeNavLinks = knowledgeCategories.map((category) => ({
  label: category.shortLabel,
  href: `/knowledge?collection=${category.id}`,
  id: category.id,
}));

export function getKnowledgeCategoryFromHash(hash: string): KnowledgeCategoryId | null {
  const id = hash.replace(/^#/, "");
  return knowledgeCategories.some((category) => category.id === id)
    ? (id as KnowledgeCategoryId)
    : null;
}

export const totalKnowledgeArticles = knowledgeCategories.reduce(
  (count, category) => count + category.articles.length,
  0,
);

export const knowledgePageMeta = {
  title: "Knowledge Center",
  description:
    "SiCore Dynamics knowledge library covering autonomous charging, wireless charging fundamentals, resonant WPT, coil design, intelligent power control, charging stations, and industry standards.",
};
