export const oemModularEngineeringPage = {
  eyebrow: "OEM Partners",
  title: "Design Service",
  subtitle:
    "Flexible engineering support, from a single design task to a complete autonomous charging solution.",
  slogan: "Build your product your way. Choose only the engineering services you need.",
  description:
    "You do not need to buy everything. Engage SiCore for one module, a subsystem, or a complete autonomous charging solution — priced and delivered to match your engineering needs.",
  heroImage: "/images/oem-integration/system-customization.png",
  heroImageAlt:
    "Modular OEM engineering building blocks for autonomous charging system design",

  intro: {
    eyebrow: "Engineering Services",
    title: "Choose only the engineering support you need.",
    lead: "Seven independent modules. Each available as a standalone service. Combine them into a complete autonomous charging solution when you are ready.",
  },

  diagram: {
    eyebrow: "How Engagement Works",
    title: "Pick the blocks your product needs",
    top: "Customer Product",
    middle: "Choose Only What You Need",
    bottom: "Production Ready",
    completeLabel: "Complete Autonomous Charging Solution",
  },

  modules: {
    eyebrow: "Seven Modules",
    title: "Engineering building blocks you can engage one at a time",
    lead: "Every module can be scoped, quoted, and delivered independently — or stacked into a full program.",
    items: [
      {
        id: "system-architecture",
        number: "01",
        shortLabel: "System",
        title: "System Architecture",
        headline: "Define the complete charging strategy for your product.",
        note: "Highest-leverage starting point for most OEM programs.",
        topics: [
          "Power Budget",
          "System Architecture",
          "Block Diagram",
          "Charging Strategy",
          "Interface Definition",
        ],
        deliverables: [
          "Architecture Document",
          "System Block Diagram",
          "Design Specification",
        ],
        standalone: "Available as a Standalone Service",
      },
      {
        id: "power-system",
        number: "02",
        shortLabel: "Power",
        title: "Power System Design",
        headline: "Engineer the power path your product depends on.",
        note: "Core SiCore expertise across conversion, protection, and thermal design.",
        topics: [
          "AC/DC",
          "DC/DC",
          "Power Distribution",
          "Protection",
          "EMC",
          "Thermal",
        ],
        deliverables: ["Schematics", "PCB", "BOM", "Test Report"],
        standalone: "✔ Standalone Project",
      },
      {
        id: "battery-system",
        number: "03",
        shortLabel: "Battery",
        title: "Battery System Engineering",
        headline: "Select, protect, and validate the energy store behind your runtime goals.",
        note: "A capability many teams need but few engineering partners cover end to end.",
        topics: [
          "Battery Selection",
          "Cell Chemistry",
          "Capacity Analysis",
          "BMS",
          "Battery Safety",
          "Runtime Estimation",
        ],
        deliverables: [
          "Battery Recommendation",
          "Battery Architecture",
          "Battery Validation",
        ],
        standalone: "✔ Standalone Project",
      },
      {
        id: "charging-electronics",
        number: "04",
        shortLabel: "Charging",
        title: "Charging Electronics",
        headline: "Build the wireless or contact charging electronics as an independent workstream.",
        note: "Can be engaged alone when architecture and battery decisions are already set.",
        topics: [
          "Wireless Charging",
          "Contact Charging",
          "Charging Controller",
          "Receiver",
          "TX",
          "Power Stage",
        ],
        deliverables: ["Charging Electronics", "Firmware", "Validation"],
        standalone: "✔ Standalone Project",
      },
      {
        id: "docking-system",
        number: "05",
        shortLabel: "Docking",
        title: "Docking System Design",
        headline: "Design the dock your machine returns to — mechanically and electrically.",
        note: "Often overlooked, yet critical for field reliability and alignment tolerance.",
        topics: [
          "Dock Structure",
          "Mechanical Alignment",
          "Waterproof",
          "Spring Contacts",
          "Wireless Dock",
          "Dock Housing",
        ],
        deliverables: ["Dock CAD", "Prototype", "Mechanical Drawing"],
        standalone: "✔ Standalone Project",
      },
      {
        id: "positioning",
        number: "06",
        shortLabel: "Positioning",
        title: "Positioning & Guidance",
        headline: "Help the machine find the dock and stay aligned for reliable charging.",
        note: "Vision, IR, magnetic, mechanical, ultrasonic, and sensor strategies as needed.",
        topics: [
          "Vision",
          "IR",
          "Magnetic Alignment",
          "Mechanical Guide",
          "Ultrasonic",
          "Sensors",
        ],
        deliverables: [
          "Position Detection",
          "Dock Alignment",
          "Guidance Strategy",
        ],
        standalone: "✔ Standalone Project",
      },
      {
        id: "product-integration",
        number: "07",
        shortLabel: "Integration",
        title: "Product Integration",
        headline: "Bring the modules together into a production-ready product design.",
        note: "The final step when you are ready to ship a complete charging solution.",
        topics: [
          "Mechanical",
          "Electrical",
          "Firmware",
          "Testing",
          "Certification",
          "Production",
        ],
        deliverables: ["Production Ready Design"],
        standalone: "Available as a Standalone Service",
      },
    ],
  },

  models: {
    eyebrow: "Typical Engagement Models",
    title: "Four ways to work with SiCore",
    lead: "Start as narrow or as complete as your roadmap requires — then expand modules when it makes sense.",
    items: [
      {
        number: "01",
        title: "Consulting",
        text: "Architecture reviews, feasibility checks, and design critiques before you commit to a build.",
        example: "Example: charging strategy review for an existing platform.",
      },
      {
        number: "02",
        title: "Single Module",
        text: "Engage one building block with a clear scope, quote, and deliverables.",
        example: "Example: dock design only.",
      },
      {
        number: "03",
        title: "Subsystem Development",
        text: "Combine related modules into a focused subsystem program.",
        example: "Example: battery + charging electronics.",
      },
      {
        number: "04",
        title: "Complete Engineering",
        text: "Hand SiCore the full autonomous charging stack — from architecture through integration.",
        example: "Example: end-to-end charging solution for a new product.",
      },
    ],
  },

  close: {
    title: "Need one module or the entire system?",
    body: "We adapt to your engineering needs. Tell us where you are in the product roadmap — we will recommend the leanest module set that moves you forward.",
    cta: { label: "Discuss Design Service", href: "/contact" },
  },
} as const;

export type OemModularEngineeringPage = typeof oemModularEngineeringPage;
